apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert
spec:
  interval: 2m
  chart:
    spec:
      chart: cert-manager
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    replicaCount: 2
    installCRDs: true