apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: stagging-cluster-issuer
spec:
  acme:
    email: admin@hasnain.dev
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-stagging-private-key
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-cluster-issuer
spec:
  acme:
    email: admin@hasnain.dev
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
      - http01:
          ingress:
            class: nginx

  