apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 2m
  chart:
    spec:
      chart: external-dns
      version: "1.9.0"
      sourceRef:
        kind: HelmRepository  
        name: external-dns
        namespace: external-dns
  values:
    fullnameOverride: external-dns
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            key: AWS_ACCESS_KEY_ID
            name: aws-creds

      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            key: AWS_SECRET_ACCESS_KEY
            name: aws-creds

    sources:
      - ingress

    txtOwnerId: "symbiosis"

    domainFilters: 
      - mhasnain.dev

    provider: aws