apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 2m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    # controller: 
    #   extraArgs: 
    #     publish-status-address: 188.40.172.121
    fullnameOverride: ingress-nginx
    publishService:
      enabled: false